/**
 * @file board_init.h
 * @brief Board-level initialisation interface for FRDM-MCXN947.
 *
 * Declares the two functions the example calls before starting the FreeRTOS
 * scheduler.  The implementation (board_init.cpp) calls the NXP SDK board
 * support functions generated by MCUXpresso Config Tools:
 *
 *   BOARD_InitBootPins()        — pin mux for ENET_QOS, LPUART, LEDs
 *   BOARD_InitBootClocks()      — system PLL → 150 MHz core clock
 *   BOARD_InitDebugConsole()    — retarget printf → LPUART4 (J-Link virtual COM)
 *
 * The Ethernet + lwIP stack is brought up by NM2_NetifInit() which the example
 * calls from main() after tcpip_init() but before vTaskStartScheduler().
 * It adds the ENET_QOS netif, starts DHCP, and registers a link-up callback
 * that signals gNetifUpSem.
 *
 * To adapt to a different SDK version or board revision:
 *   1. Regenerate board.c/pin_mux.c/clock_config.c with Config Tools.
 *   2. Adjust ENET_QOS_NETIF_INIT_FN (ethernetif_init) if the SDK port renamed it.
 *   3. Adjust BOARD_ENET_TX_BD_NUM / BOARD_ENET_RX_BD_NUM in board.h if needed.
 *
 * Copyright (c) 2026 AmeNote Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#pragma once
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initialise clocks, pin mux, and the debug UART.
 *
 * Must be called before the FreeRTOS scheduler starts and before any
 * printf output.  Does NOT initialise the Ethernet MAC or lwIP.
 */
void NM2_BoardInit(void);

/**
 * @brief Add the ENET_QOS netif to lwIP, but do not bring it up yet.
 *
 * Must be called from main(), after tcpip_init() returns, while still in
 * single-threaded context (before vTaskStartScheduler). Registers the
 * netif with an all-zero address and leaves it down -- deliberately split
 * from starting DHCP or assigning a static address (NM2_NetifStartDhcp() /
 * NM2_NetifSetStatic() below), since which of those to use is a runtime
 * setup-menu choice (SessionTask.cpp's Network -- [D]HCP or [S]tatic IP
 * prompt) decided after the scheduler starts, not something known yet at
 * this call site.
 *
 * @param mac6  Pointer to a 6-byte MAC address (OUI + device-specific bytes).
 *              If NULL, a locally-administered default is used.
 */
void NM2_NetifAdd(const uint8_t *mac6);

/**
 * @brief Bring the netif up and start DHCP.
 *
 * Called once, from vSessionTask after the DHCP-vs-static setup-menu
 * choice is known (or after the boot-time setup gate times out with the
 * default choice, DHCP). Must be called with LOCK_TCPIP_CORE() held (the
 * caller is a FreeRTOS task running after vTaskStartScheduler(), not the
 * single-threaded pre-scheduler context NM2_NetifAdd() runs in).
 */
void NM2_NetifStartDhcp(void);

/**
 * @brief Assign a static IPv4 address/netmask/gateway/DNS and bring the
 * netif up (no DHCP).
 *
 * Same call-site/locking requirements as NM2_NetifStartDhcp(). Each
 * parameter is a dotted-decimal string (e.g. "192.168.1.200"); returns
 * false without changing anything if any of ip/netmask/gateway fails to
 * parse (dns may be NULL/empty to skip setting a DNS server).
 */
bool NM2_NetifSetStatic(const char *ip, const char *netmask, const char *gateway, const char *dns);

/**
 * @brief Non-blocking character read from the debug console.
 *
 * Returns the character (0–255) if one is available in the LPUART receive
 * buffer, or -1 if no character is pending.  Safe to call from any task
 * without holding a mutex (backed by a FreeRTOS queue filled by the LPUART
 * receive ISR).
 */
int NM2_GetCharNonBlocking(void);

/**
 * @brief Power up and clock the USB1 ChipIdea High-Speed controller + PHY.
 *
 * FRDM-MCXN947's USB-C connector is wired to USB1 (rhport 1, High-Speed);
 * USB0 (KHCI, Full-Speed) is not used by this example. Must be called before
 * tusb_init() / tud_init(). Register sequence follows TinyUSB's own
 * hw/bsp/mcx/family.c board_init() for BOARD_TUD_RHPORT==1 (SPC/DCDC voltage
 * bump, USB HS PHY PLL from the 20-30 MHz crystal, then PHY calibration) --
 * kept here rather than pulling in TinyUSB's whole board.c/pin_mux.c/
 * clock_config.c, which would collide with this example's own
 * NM2_BoardInit()/BOARD_InitBootPins()/BOARD_InitBootClocks() (same
 * NXP-generated function names, different Config Tools project).
 */
void NM2_UsbHsInit(void);

#ifdef __cplusplus
}
#endif
