/**
 * @file board_init.h
 * @brief Board-level initialisation interface for FRDM-MCXN947.
 *
 * Declares the two functions the example calls before starting the FreeRTOS
 * scheduler.  The implementation (board_init.cpp) calls the NXP SDK board
 * support functions generated by MCUXpresso Config Tools:
 *
 *   BOARD_InitBootPins()        — pin mux for ENET_QOS, LPUART, LEDs
 *   BOARD_InitBootClocks()      — system PLL → 150 MHz core clock
 *   BOARD_InitDebugConsole()    — retarget printf → LPUART4 (J-Link virtual COM)
 *
 * The Ethernet + lwIP stack is brought up by NM2_NetifInit() which the example
 * calls from main() after tcpip_init() but before vTaskStartScheduler().
 * It adds the ENET_QOS netif, starts DHCP, and registers a link-up callback
 * that signals gNetifUpSem.
 *
 * To adapt to a different SDK version or board revision:
 *   1. Regenerate board.c/pin_mux.c/clock_config.c with Config Tools.
 *   2. Adjust ENET_QOS_NETIF_INIT_FN (ethernetif_init) if the SDK port renamed it.
 *   3. Adjust BOARD_ENET_TX_BD_NUM / BOARD_ENET_RX_BD_NUM in board.h if needed.
 *
 * Copyright (c) 2026 AmeNote Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#pragma once
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initialise clocks, pin mux, and the debug UART.
 *
 * Must be called before the FreeRTOS scheduler starts and before any
 * printf output.  Does NOT initialise the Ethernet MAC or lwIP.
 */
void NM2_BoardInit(void);

/**
 * @brief Add the ENET_QOS netif to lwIP and start DHCP.
 *
 * Must be called from main(), after tcpip_init() returns, while still in
 * single-threaded context (before vTaskStartScheduler).
 *
 * @param mac6  Pointer to a 6-byte MAC address (OUI + device-specific bytes).
 *              If NULL, a locally-administered default is used.
 */
void NM2_NetifInit(const uint8_t *mac6);

/**
 * @brief Non-blocking character read from the debug console.
 *
 * Returns the character (0–255) if one is available in the LPUART receive
 * buffer, or -1 if no character is pending.  Safe to call from any task
 * without holding a mutex (backed by a FreeRTOS queue filled by the LPUART
 * receive ISR).
 */
int NM2_GetCharNonBlocking(void);

#ifdef __cplusplus
}
#endif
